---
- name: question2
  hosts: all
  tasks:
    - name: EX294_BASE
      ansible.builtin.yum_repository:
        name: EX294_BASE
        description: EX294 base software
        baseurl: http://content/rhel9.0/x86_64/dvd/BaseOS
        gpgcheck: yes
        gpgkey: http://content/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
        enabled: yes
    - name: EX294_STREAM
      ansible.builtin.yum_repository:
        name: EX294_STREAM
        description: EX294 stream software
        baseurl: http://content/rhel9.0/x86_64/dvd/AppStream
        gpgcheck: yes
        gpgkey: http://content/rhel9.0/x86_64/dvd/RPM-GPG-KEY-redhat-release
        enabled: yes