---
- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: start httpd
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes

- name: start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open port
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- template:
    src: index.html.j2
    dest: /var/www/html/index.html