---
- name: Q13
  hosts: all
  tasks:
    - name: p1
      ansible.builtin.get_url:
        url: http://classroom/materials/hwreport.empty
        dest: /root/hwreport.txt

    - name: p2
      ansible.builtin.lineinfile:
        path: /root/hwreport.txt
        regexp: '^HOST='
        line: HOST={{ansible_hostname}}

    - name: p3                           
      ansible.builtin.lineinfile:        
        path: /root/hwreport.txt         
        regexp: '^MEMORY='                 
        line: MEMORY={{ansible_memtotal_mb}}MB

    - name: p4                           
      ansible.builtin.lineinfile:        
        path: /root/hwreport.txt         
        regexp: '^BIOS='                 
        line: BIOS={{ansible_bios_version}}

    - name: p5                           
      ansible.builtin.lineinfile:        
        path: /root/hwreport.txt         
        regexp: '^DISK_SIZE_VDA='                 
        line: DISK_SIZE_VDA={{ansible_devices.vda.size}}

    - name: p6                           
      ansible.builtin.lineinfile:        
        path: /root/hwreport.txt         
        regexp: '^DISK_SIZE_VDB='                 
        line: DISK_SIZE_VDB={{ansible_devices.vdb.size | default('NONE', true)}}