---
- name: Q3_1
  hosts: dev,test,prod
  tasks:
    - name: p1
      ansible.builtin.yum:
        name:
          - php
          - mariadb
        state: present

- name: Q3_2
  hosts: dev
  tasks:
    - name: p2
      ansible.builtin.yum:
        name: "@RPM Development Tools"
        state: present

- name: Q3_3
  hosts: dev
  tasks:
    - name: p3
      ansible.builtin.yum:
        name: "*"
        state: latest