---
- name: Q9
  hosts: all
  tasks:
    - block:
      - name: create lv
        community.general.lvol:
          vg: research
          lv: data
          size: 1500

      - name: ext4 format
        community.general.filesystem:
          fstype: ext4
          dev: /dev/research/data

      rescue:
        - name: error
          ansible.builtin.debug:
            msg: "Could not create logical volume of that size"

        - name: create 800m
          community.general.lvol:
            vg: research
            lv: data
            size: 800

        - name: ext4 format
          community.general.filesystem:
            fstype: ext4
            dev: /dev/research/data
          when: ansible_lvm.vgs.research is defined

    - name: Check if volume group exists
      ansible.builtin.debug:
        msg: "Volume group does not exist"
      when: ansible_lvm.vgs.research is not defined