---
- name: Q9
  hosts: all
  tasks:
    - name: shell register
      shell: "vgdisplay research"
      register: aa
      ignore_errors: yes

    - name: judge1
      debug:
        msg: Volume group done not exist
      when: aa.rc != 0

    - name: main11
      block:
        - name: create 1500
          community.general.lvol:
            vg: research
            lv: data
            size: 1500
      rescue:
        - name: err msg
          debug:
            msg: Could not create logical volume of that size
        - name: create 800                                  
          community.general.lvol:                            
            vg: research                                     
            lv: data                                         
            size: 800   

    - name: format
      community.general.filesystem:
        dev: /dev/research/data
        fstype: ext4